### ISSUE TITLE
Error delivering notification

### ISSUE THREAD

**Issue by Sicmatr1x** [KnuffApp/Knuff#84]
```
Connection failed: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9858, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x600003e7dd10 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9858, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9858}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.push.apple.com/3/device/e5007b1d4f533e03871e1142ed3246d267cd58334e97df5141d9b8ed92a9ef78, NSErrorFailingURLStringKey=https://api.push.apple.com/3/device/e5007b1d4f533e03871e1142ed3246d267cd58334e97df5141d9b8ed92a9ef78, _kCFStreamErrorDomainKey=3}
```

**Comment by pjamroz** [comment]
Same here. Have you found any solution?

**Comment by iOSChatomaps** [comment]
same , any solution ?

**Comment by blommegard** [comment]
This should be fixed with [1.3](https://github.com/KnuffApp/Knuff/releases/tag/v1.3).

**Comment by brunomunizaf** [comment]
I'm still facing it on 1.3(4) 

Connection failed: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9858, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x600003219770 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9858, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9858}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.development.push.apple.com/3/device/........, NSErrorFailingURLStringKey=https://api.development.push.apple.com/3/device/........, _kCFStreamErrorDomainKey=3}

**Comment by sidelux** [comment]
Same here, with 1.3

**Comment by sasosecnjak** [comment]
Same, with 1.3(4)
